### ISSUE TITLE
If run MCIS 'Reboot' using MapUI, the reboot command is not executed properly.

### ISSUE THREAD

**Issue by innodreamer** [cloud-barista/cb-mapui#117]
**What happened**
: MapUI를 이용해 MCIS Control에서 특정 MCIS를 선택해서 'Reboot' 버튼을 클릭할 경우, 제대로 reboot command가 실행되지 않음.
(참고) Reboot 기능 외의 Suspend, Resume 등의 버튼은 정상 작동함. 또한, CB-SP API로 실행할경우 reboot이 제대로 실행됨.

**What you expected to happen**
: MapUI에서 MCIS의 VM들이 정상적으로 구동되어 running 하고 있는 상태에서 'Reboot' 버튼을 클릭할 경우 해당 MCIS에 속한 VM들이 모두 reboot 되어야함. 

**How to reproduce it (as minimally and precisely as possible)**
: MCIS dynamic 기능으로 NHN Cloud, NCP VPC 등의 클라우드 대상으로 VM까지의 자원들을 생성 후, MCIS Control에서 특정 MCIS를 선택한 후 'Reboot' 버튼을 클릭

**Environment**
- Source version or branch: 현재 기준 최신 버전의 MapUI container로 실행했음.

**Proposed solution**
: MCIS Control에서 특정 MCIS를 선택해서 'Reboot' 버튼을 클릭할 경우, 그 기능에 해당하는 CB-TB API가 제대로 실행되는지 확인

**Comment by seokho-son** [comment]
@innodreamer 
- MapUI와 CB-TB 사이의 API 요청에는 문제가 없는 것으로 보입니다. (path 및 action 요청에 문제없음)
- AWS VM의 경우, action=reboot 정상 동작하는 것을 확인하였습니다. 참고로, reboot 명령은 CSP에 따라서(대부분의 CSP) 매우 빠르게 처리되므로, rebooting 상태를 확인하기 어려운 경우가 많습니다. Spider 드라이버 내부적으로 suspend-resume 을 활용하여 reboot을 에뮬레이션 하는 경우에만 rebooting 상태를 확인할 수 있는 경우가 많은 것 같습니다.

NHN Cloud, NCP VPC 에 대해 직접 테스트를 해보지는 않았지만, 문제가 있더라도 MapUI의 이슈는 아닐 것으로 판단됩니다.
혹시 CB-TB API로 직접 테스트하시는 경우에도 문제가 발생하나요?

**Comment by innodreamer** [comment]
@seokho-son 
아... 제가 추가적으로 기입해놓지는 않았는제 CB-TB의 MCIS 제어 API로 테스트해봐도 동일한 문제가 발생합니다.
MapUI에서의 API call 문제라기보다 CB-TB의 API의 문제인거 같습니다.

참고로, CB-SP에서 테스트시에는 CSP console에서 VM들이 잠깐 혹은 좀 시간을 들여서 reboot 되는 상황이 보이고, CB-TB의 API로 실행했을때는 그대로 running하고 있는 상태로 있었습니다.
