### ISSUE TITLE
Container version not showing map UI properly

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-mapui#40]
**What happened**
컨테이너 이미지를 통해 MapUI 실행시,
0.4.7, 0.5.1 ~ latest 등에서 
`Show CSP` 버튼 클릭 이후부터 이미지 리소스들이 정상적으로 화면에 출력되지 않는 문제 발생

 - 0.4.5에서는 정상 동작함
 - 소스에서 빌드시 정상 동작함

**What you expected to happen**
정상 동작

**How to reproduce it (as minimally and precisely as possible)**
컨테이너로 실행

**Anything else we need to know?**

- 0.5.1로 컨테이너 구동한 경우, dist 디렉토리 형상
/app/dist/img # son@son:~/go/src/github.com/cloud-barista/cb-tumblebug$ sudo docker exec -it cb-mapui /bin/sh
/app # cd dist/
/app/dist # ls
app.d54c21f1.js                 decoder.worker.8445e99e.js.map  jpeg.40572f14.js                lzw.9136ad22.js.map
app.d54c21f1.js.map             deflate.df6bb2fb.js             jpeg.40572f14.js.map            packbits.6e14c999.js
app.fffbceca.css                deflate.df6bb2fb.js.map         lerc.5dd7de19.js                packbits.6e14c999.js.map
app.fffbceca.css.map            img                             lerc.5dd7de19.js.map            raw.219655b0.js
decoder.worker.8445e99e.js      index.html                      lzw.9136ad22.js                 raw.219655b0.js.map

- 0.4.5로 컨테이너 구동한 경우, dist 디렉토리 형상
/app/dist/img # son@son:~/go/src/github.com/cloud-barista/cb-tumblebug$ sudo docker exec -it cb-mapui /bin/sh
/app # cd dist/
/app/dist # ls
app.28811440.js                 decoder.worker.8445e99e.js      jpeg.183c02ed.js                lzw.9136ad22.js
app.28811440.js.map             decoder.worker.8445e99e.js.map  jpeg.183c02ed.js.map            lzw.9136ad22.js.map
app.e31bb0bc.css                deflate.91d00981.js             jpeg.40572f14.js                packbits.6e14c999.js
app.e31bb0bc.css.map            deflate.91d00981.js.map         jpeg.40572f14.js.map            packbits.6e14c999.js.map
app.e31bb0bc.js                 deflate.df6bb2fb.js             lerc.180069fb.js                packbits.d75d8315.js
app.e31bb0bc.js.map             deflate.df6bb2fb.js.map         lerc.180069fb.js.map            packbits.d75d8315.js.map
app.fffbceca.css                img                             lerc.5dd7de19.js                raw.219655b0.js
app.fffbceca.css.map            index.html                      lerc.5dd7de19.js.map            raw.219655b0.js.map
decoder.worker.69db4f0b.js      index.js                        lzw.3fe7a5dc.js                 raw.ca80317c.js
decoder.worker.69db4f0b.js.map  index.js.map                    lzw.3fe7a5dc.js.map             raw.ca80317c.js.map

- 관련 에러 메시지
[Get Connection list from CB-Tumblebug API]
Immediate.js:333 Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at CanvasImmediateRenderer.drawImages_ (http://--:1324/app.e31bb0bc.js:37203:17)
    at CanvasImmediateRenderer.drawMultiPoint (http://--:1324/app.e31bb0bc.js:37532:12)
    at CanvasImmediateRenderer.drawGeometry (http://--:1324/app.e31bb0bc.js:37418:14)
    at drawMCIS (http://--:1324/app.e31bb0bc.js:120741:19)
    at TileLayer.<anonymous> (http://--:1324/app.e31bb0bc.js:120826:3)
    at TileLayer.Target.dispatchEvent (http://--:1324/app.e31bb0bc.js:3224:24)
    at CanvasTileLayerRenderer.CanvasLayerRenderer.dispatchRenderEvent_ (http://--:1324/app.e31bb0bc.js:35027:13)
    at CanvasTileLayerRenderer.CanvasLayerRenderer.postRender (http://--:1324/app.e31bb0bc.js:35048:10)
    at CanvasTileLayerRenderer.renderFrame (http://--:1324/app.e31bb0bc.js:50713:10)
    at TileLayer.Layer.render (http://--:1324/app.e31bb0bc.js:4972:28)

**Comment by seokho-son** [comment]
PTAL @jihoon-seo 
Thanks!

**Comment by seokho-son** [comment]
@jihoon-seo 관련 현황 문의 드립니다. :)

**Comment by jihoon-seo** [comment]
[v0.4.5]
![image](https://user-images.githubusercontent.com/46767780/166418637-3645d16e-8e09-42f1-a528-06a46d067bba.png)

[v0.4.6] 에서 "Show CSP" 및 "Total CSP regions" 관련 기능이 추가되면서, 해당 에러의 원인도 추가된 것으로 보입니다.
(v0.4.6 에서도 재현 됨을 확인하였음)
![image](https://user-images.githubusercontent.com/46767780/166418709-8636185b-7b6c-44b9-ac7e-fad7542b99fe.png)

---

제 추정으로는
https://github.com/cloud-barista/cb-mapui/blob/da053cba6151ee5d3809d2cdf07d49a1e9d83e18/index.js#L2017-L2018

`iconStyleAzure` (또는 `setStyle(iconStyleAzure)` 된 `vectorContext`, 또는 something else) 가 load 완료됐는지 확인하고
load 완료되어야 `vectorContext.drawGeometry` 하도록 수정하면 될 것 같은데
잘 안되네요.. 🤔

**Comment by seokho-son** [comment]
@jihoon-seo `type=module` 관련 이슈는 해결하셨나용? :)

**Comment by jihoon-seo** [comment]
Resolved by #41 😊

---

`type=module` 관련 이슈는 
`package.json` 에 써 있는 대로
```
    "parcel": "^2.0.1",
    "parcel-bundler": "^1.12.5"
```
버전을 설치하니 해결되었습니다. 😊

**Comment by jihoon-seo** [comment]
실행 시 해당 에러가 발생하는 0.4.6 ~ 0.5.1 컨테이너 이미지를 [Docker Hub](https://hub.docker.com/r/cloudbaristaorg/cb-mapui/tags) 및 GHCR에서 삭제하는 방안도 있겠습니다. 😊

**Comment by seokho-son** [comment]
@jihoon-seo 그렇네요^^ 그럼! 삭제를 부탁 드립니다.

**Comment by seokho-son** [comment]
@jihoon-seo 아, 0.5.0이랑 0.5.1은 남겨두면 좋을 것 같습니다. (잠시)
프로비저닝 기능 빼고 상태 보기 형태로는 일부 동작하므로..^^; 사용하는 분이 계실까바

**Comment by seokho-son** [comment]
@yunkon-kim 주로 MapUI 무슨 버전을 사용하고 계신가요?

**Comment by yunkon-kim** [comment]
@seokho-son 마지막으로 사용했을때 0.5.1 버전을 사용했고요. 최근 3주 동안은 사용하지 않았습니다 ^^
