### ISSUE TITLE
Dockerfile redundant codes

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-mapui#47]
Dockerfile 에 중복 코드 및 이미지 사이즈 등을 고려하여 개선 필요

**Comment by seokho-son** [comment]
@jihoon-seo 
fixed by #50 ?

**Comment by jihoon-seo** [comment]
컨테이너 이미지 크기가
0.5.1 은 260MB
최신은 491MB 으로
크기가 커서 좀 아쉽긴 하지만..
일단은 close 해도 될 것 같습니다. 😊
