### ISSUE TITLE
`confirm(), prompt(), alert()` enhancement

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-mapui#48]
흠.. 이러한 경우에는 confirm(), prompt(), alert() 등을 그대로 쓰기보다는
jQuery UI 같은 것을 쓰는 것이 더 좋을 것 같네요.. ㅎㅎ
- confirm() → [jQuery UI - Dialog - Modal confirmation](https://jqueryui.com/dialog/#modal-confirmation)
- prompt() → [jQuery UI - Dialog - Modal form](https://jqueryui.com/dialog/#modal-form)
- alert() → [jQuery UI - Dialog - Basic dialog](https://jqueryui.com/dialog/#default) or [jQuery UI - Dialog - Modal message](https://jqueryui.com/dialog/#modal-message)

[SweetAlert2](https://sweetalert2.github.io/) 라는 것도 있습니다. 😊

_Originally posted by @jihoon-seo in https://github.com/cloud-barista/cb-mapui/issues/45#issuecomment-1128296284_

**Comment by jihoon-seo** [comment]
[SweetAlert2]
- [confirm](https://inpa.tistory.com/entry/SweetAlert2-%F0%9F%93%9A-%EC%84%A4%EC%B9%98-%EC%82%AC%EC%9A%A9#--%--Confirm%EC%-C%BC%EB%A-%-C%--%EC%--%AC%EC%-A%A-%ED%--%--%EA%B-%B-)
- [prompt](https://inpa.tistory.com/entry/SweetAlert2-%F0%9F%93%9A-%EC%84%A4%EC%B9%98-%EC%82%AC%EC%9A%A9#--%--Prompt%EB%A-%-C%--%EC%--%AC%EC%-A%A-%ED%--%--%EA%B-%B-)
- [alert](https://inpa.tistory.com/entry/SweetAlert2-%F0%9F%93%9A-%EC%84%A4%EC%B9%98-%EC%82%AC%EC%9A%A9#--%--%EC%--%--%EC%--%-C%--%EA%B-%B-%EB%B-%B-%--Alert%--%EC%--%AC%EC%-A%A-%ED%--%--%EA%B-%B-)

**Comment by seokho-son** [comment]
@jihoon-seo 혹시 작업 중이신가요~?

참고로, 

package.json 에 추가하고
```diff
  "dependencies": {
    "axios": "^0.24.0",
    "buffer": "^6.0.3",
    "csv-parser": "^3.0.0",
    "http": "0.0.1-security",
    "ol": "^6.14.1",
+   "sweetalert2": "^11.4.14"
  },
```

index.js에 추가하고
```
// ES6 Modules or TypeScript
import Swal from 'sweetalert2'
const Swal = require('sweetalert2')
```

https://sweetalert2.github.io/#examples
이런 식으로 예시를 추가해보니, 동작하는 것 같네요 :)
```
    Swal.fire({
      title: 'Please input the number of VMs to create (1 ~ 10)',
      text: JSON.stringify(res.data[0], null, 2),
      input: 'text',
      inputAttributes: {
        autocapitalize: 'off'
      },
      showCancelButton: true,
      confirmButtonText: 'Confirm',
      showLoaderOnConfirm: true,
      allowOutsideClick: () => !Swal.isLoading()
    }).then((result) => {
      if (result.isConfirmed) {
        Swal.fire({
          text: `VM * ${result.value}`,
        })
      }
    })
```

![image](https://user-images.githubusercontent.com/5966944/169240690-16a2183c-162f-4e59-b87d-487cb520d9d5.png)
