### ISSUE TITLE
Change branch name master to main

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-mapui#77]
**What would you like to be enhanced**
: 기본 브랜치의 명칭 변경

**Why is this needed**
: https://github.com/cloud-barista/cb-coffeehouse/issues/104 - Inclusive Naming Initiative

**Proposed solution**
: Change branch name master to main

**Comment by seokho-son** [comment]
@jihoon-seo 어떻게 생각하시나요?
(ref @yunkon-kim)

**Comment by jihoon-seo** [comment]
저는 좋습니다 lgtm 입니다 ㅎㅎㅎ
